p8105\_hw6\_cac2225
================
Courtney Chan
November 26, 2018

Homework 6
==========

Problem 0
---------

A github repo and local R project was created, an Rmd file was produced, knitted, and committed to github.

Problem 1
---------

First loading all necessary packages

``` r
library(tidyverse)
```

    ## -- Attaching packages --------------------------------------- tidyverse 1.2.1 --

    ## v ggplot2 3.0.0     v purrr   0.2.5
    ## v tibble  1.4.2     v dplyr   0.7.6
    ## v tidyr   0.8.1     v stringr 1.3.1
    ## v readr   1.1.1     v forcats 0.3.0

    ## -- Conflicts ------------------------------------------ tidyverse_conflicts() --
    ## x dplyr::filter() masks stats::filter()
    ## x dplyr::lag()    masks stats::lag()

The csv file is imported using the read\_csv function and the dataset is cleaned.

``` r
homicide = read_csv("./data/homicide-data.csv") %>% 
  janitor::clean_names()
```

    ## Parsed with column specification:
    ## cols(
    ##   uid = col_character(),
    ##   reported_date = col_integer(),
    ##   victim_last = col_character(),
    ##   victim_first = col_character(),
    ##   victim_race = col_character(),
    ##   victim_age = col_character(),
    ##   victim_sex = col_character(),
    ##   city = col_character(),
    ##   state = col_character(),
    ##   lat = col_double(),
    ##   lon = col_double(),
    ##   disposition = col_character()
    ## )

A city\_state variable is created using the functions paste and mutate. Also a "solved" variable is created to indicate which cases have or have not been solved based on homework 5's prompt. The number of unsolved homicides is defined as those for which the disposition is “Closed without arrest” or “Open/No arrest”). City\_states Dallas, TX, Pheonix, AZ, Kansas City, MO and Tulsa, AL are filtered out of the dataset.

``` r
homicide = homicide %>% 
  mutate(city_state = str_c(city,", ",state)) %>% 
  mutate(solved = recode(disposition, "Closed without arrest" = "Unsolved", "Open/No arrest" = "Unsolved", "Closed by arrest" = "Solved")) %>% 
  filter(city_state != "Dallas, TX", city_state != "Phoenix, AZ", city_state != "Kansas City, MO", city_state != "Tulsa, AL")
```

The victim race variable is modified to be binary and for the catagory "White" to be defined as the reference catagory. Hispanic, Asian, Black, Other and Unknown were coded as "Non-white".

``` r
homicide = homicide %>% 
  mutate(victim_race = recode(victim_race, "Black" = "Non-white", "Hispanic" = "Non-white", "Asian" = "Non-white", "Other" = "Non-white", "Unknown" = "Non-white")) %>%  mutate(victim_race = factor(victim_race, levels = c("Non-white", "White")))

is.factor(homicide$victim_race)
```

    ## [1] TRUE

Victim\_age is first checked to see whether it is a numeric variable. Since it is not, the "unknown" category is first recoded as "NA". Then victim\_age is defined as a numeric variable. It is checked again to see whether it was converted successfully into an numeric variable.

``` r
is.numeric(homicide$victim_age)
```

    ## [1] FALSE

``` r
homicide = homicide %>% 
 mutate(victim_age = as.numeric(victim_age)) %>% 
  mutate(factor(solved)) %>% 
  mutate(solved = factor(solved, levels = c("Solved", "Unsolved")))
```

    ## Warning in evalq(as.numeric(victim_age), <environment>): NAs introduced by
    ## coercion

``` r
is.numeric(homicide$victim_age)
```

    ## [1] TRUE

``` r
is.factor(homicide$solved)
```

    ## [1] TRUE

``` r
baltimore = homicide %>% 
  filter(city_state == "Baltimore, MD") %>% 
  glm(solved ~ victim_age +  victim_sex + victim_race, data = ., family = binomial())

baltimore %>% 
  broom::tidy() %>% 
  mutate(OR = exp(estimate)) %>% 
  mutate(conf.low = exp(estimate - (1.96*std.error)),
         conf.high = exp(estimate + (1.96*std.error))) %>% select(term, estimate, OR, conf.low, conf.high) %>% 
  filter(term == "victim_raceWhite")
```

    ## # A tibble: 1 x 5
    ##   term             estimate    OR conf.low conf.high
    ##   <chr>               <dbl> <dbl>    <dbl>     <dbl>
    ## 1 victim_raceWhite   -0.820 0.441    0.313     0.620

For cases in Baltimore, MD, the point estimate describing the relationship between the outcome of solved homicides and the predictor victim race, adjusting for victim age and victim sex is 0.441, with a 95% confidence interval of 0.313 to 0.62.

For cases in Baltimate, MD, the odds of having a solved case amongst those who are non-white is 0.441 times the odds of having a solved case amongst those who are white, adjusting for victim age and sex. We are 95% confident that the true odds ratio lies between 0.313 and 0.62.

``` r
df_homicide = 
  homicide %>%
  group_by(city_state) %>% 
  nest() %>% 
  mutate(model = map(data, ~glm(solved ~ victim_age +  victim_sex + victim_race, data = ., family = binomial())), 
model = map(model, broom::tidy)) %>% 
  select(-data) %>% 
  unnest() %>% 
   mutate(OR = exp(estimate)) %>% 
  mutate(conf.low = exp(estimate - (1.96*std.error)),
         conf.high = exp(estimate + (1.96*std.error))) %>% select(city_state, term, estimate, OR, conf.low, conf.high) %>% 
  filter(term == "victim_raceWhite")
```

Glm is applied to each city\_state and an OR with 95% confidence intervals is calculated for each city\_state, comparing the odds of the case being solved, between non-whites and whites, adjusting for sex and age.

``` r
df_homicide %>% 
  ggplot(aes(fct_reorder(city_state, desc(OR)), OR)) + geom_bar(stat = "identity") + geom_errorbar(aes(ymin = conf.low, ymax = conf.high)) + theme(axis.text.x = element_text(angle = 90)) + ggtitle("estimated adjusted ORs and confidence intervals per city, state") + xlab("city, state") + ylab("adjusted estimate ORs of solved cases, non- vs whites")
```

![](p8105_hw6_cac2225_files/figure-markdown_github/plot%20estimate%20ORs%20and%20CIs%20for%20each%20city-1.png)

Problem 2
---------
